### department 등록
POST http://localhost:8080/department
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "id":"CS0001",
  "name":"고객서비스1팀"
}

### department 조회
GET http://localhost:8080/department/CS0001
X-USER-ID:nhnacademy


### department 수정
PUT http://localhost:8080/department/CS0001
Content-Type: application/json
X-USER-ID:nhnacademy

{
  "name" : "CS1팀"
}

### department 삭제
DELETE http://localhost:8080/department/CS0001
X-USER-ID:nhnacademy


### 조회
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:nhnacademy

### xml
GET http://localhost:8080/department-members?departmentIds=A9004&format=xml
Accept:application/xml
X-USER-ID:nhnacademy


### 400 bad request - missing parameter
GET http://localhost:8080/department-members
Accept:application/json
X-USER-ID:nhnacademy

### 400 bad request - empty parameter
GET http://localhost:8080/department-members?departmentIds=
Accept:application/json
X-USER-ID:nhnacademy

### 400 bad request - application/csv
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/csv
X-USER-ID:nhnacademy

### 401 - x-user-id marco
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:marco

### 401 - x-user-id empty
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json
X-USER-ID:

### 401 - x-user-id null
GET http://localhost:8080/department-members?departmentIds=L1001
Accept:application/json

